### PR TITLE
Command to compile is actually prepublish

### PR DESCRIPTION
**Pull request by johnjbarton**

### CODE REVIEW

**Comment by bcaudan** [comment]
If we want to do that we should probably also update the use of tsc in package.json scripts.

I appreciate the will of not duplicate behaviors but I would prefer to keep prepublish and compilation as two separate things. In case of adding others operations in the prepublish command.

Is that understandable or am I too picky on this?

**Comment by johnjbarton** [comment]
Well AFAICT, there are not two things, prepublish and compile, just one thing that works:

```sh
[jasmine-spec-reporter (compile-is-prepublish)]$ npm run tsc
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tsc"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! missing script: tsc
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /work/jasmine-spec-reporter/npm-debug.log
[jasmine-spec-reporter (compile-is-prepublish)]$ npm run prepublish

> jasmine-spec-reporter@3.2.0 prepublish /work/jasmine-spec-reporter
> tsc

[jasmine-spec-reporter (compile-is-prepublish)]$ 
```

**Comment by bcaudan** [comment]
ah ah ok, nice catch!

So, it means that I never just compile the sources. 
Had you have the need to compile the sources or did you just follow the readme and run into this issue?

If it is useful, we could put back the tsc script, otherwise I would be in favor of removing this from the readme.

**Comment by bcaudan** [comment]
@johnjbarton thanks for all your feedbacks!

Nice work with you on the past few days ;)

**Pull request merged**
