### PR TITLE
pending workaround for protractor

### PR DESCRIPTION
**Pull request by digitalkaoz**
protractor marks pending tests as failed, this fix corrects this behavior...

### CODE REVIEW

**Comment by digitalkaoz** [comment]
https://github.com/angular/protractor/issues/2454 once this is merged, we can remove this workaround

**Comment by bcaudan** [comment]
Hi @digitalkaoz,

If you want to go forward on this issue, there is a test on protractor integration, I suggest you to add your failing case and then add the code that make it pass.

Let me know if there is any trouble.

**Comment by digitalkaoz** [comment]
@bcaudan i added an integration test case... travis is green

**Comment by bcaudan** [comment]
I've looked into it and I do not wish to integrate it for two reasons:
- it is a long running issue on protractor side, I have no idea when this behavior will be fix so I do not want to maintain this behavior for ages.
- IMO, this workaround does not provide much help since protractor exit code is still 1, so your test is still failed.

Does it sound fair?

**Comment by digitalkaoz** [comment]
Yeah i guessed so...sad that protractor didnt fixed that issue

Bastien Caudan <notifications@github.com> schrieb am Sa., 15. Apr. 2017,
12:37:

**Pull request closed without merging**
