### PR TITLE
Fix for #392

### PR DESCRIPTION
**Pull request by apla**
Allows using with `jasmine --reporter=jasmine-spec-reporter`

### CODE REVIEW

**Comment by piecioshka** [comment]
@bcaudan please merge :pray:

**Comment by bcaudan** [comment]
I have tested it locally without success.

`exports.default` does not seem to be equivalent to `module.exports`.
Am I missing something?

**Comment by piecioshka** [comment]
Eh @bcaudan why you don't merge?

**Comment by bcaudan** [comment]
Hi @piecioshka, as I said in the previous comment, I have not been able to make it work and add some thoughts on the original issue: https://github.com/bcaudan/jasmine-spec-reporter/issues/392#issuecomment-485237743
Due to the lack of activity, I decided to close this PR.
I would be glad to reopen it if someone make it work.

**Pull request closed without merging**
